### ISSUE TITLE
Login consistently takes 30s-60s  to complete

### ISSUE THREAD

**Issue by ghstahl** [Azure/login#20] opened 2020-04-15 19:20 UTC
Is this a function of the VMs that github provisions, this action, or the az cli itself?  

```
az login 27s (UP TO 60 seconds)
Login successful.
Run azure/login@v1
C:\windows\system32\cmd.exe /D /S /C ""C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" --version"
WARNING: You have 2 updates available. Consider updating your CLI installation. Instructions can be found at https://docs.microsoft.com/en-us/cli/azure/install-azure-cli
azure-cli                          2.2.0 *

command-modules-nspkg              2.0.3
core                               2.2.0 *
nspkg                              3.0.4
telemetry                          1.0.4

Extensions:
azure-devops                      0.17.0

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\python.exe'
Extensions directory 'C:\Program Files\Common Files\AzureCliExtensionDirectory'

Python (Windows) 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 02:47:15) [MSC v.1900 32 bit (Intel)]

Legal docs and information: aka.ms/AzureCliLegal




Please let us know how we are doing: https://aka.ms/clihats
Login successful.
```

**Comment by eaarora-ms** [comment] 2020-05-15 07:01
@ghstahl I am afraid I do not understand your query. With the Azure login Action, you can automate your workflow to do an Azure login using Azure service principal and run Az CLI and Azure PowerShell scripts. Are you facing any issue in using this action?

**Comment by ljtill** [comment] 2020-06-08 12:46
Also experiencing this behavior, we're using Azure PowerShell process. Runs can vary from 30 seconds to 4 minutes to complete.

```yaml
- name: Authenticate session
        uses: azure/login@v1.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true
```

```text
2020-06-08T12:33:20.0747185Z ##[group]Run azure/login@v1.1
2020-06-08T12:33:20.0747527Z with:
2020-06-08T12:33:20.0748054Z   creds: ***
2020-06-08T12:33:20.0748329Z   enable-AzPSSession: true
2020-06-08T12:33:20.0748820Z env:
2020-06-08T12:33:20.0749734Z   AZURE_CREDENTIALS: ***
2020-06-08T12:33:20.0751332Z   PSModulePath: /usr/share/az_4.1.0:/home/runner/.local/share/powershell/Modules:/usr/local/share/powershell/Modules:/opt/microsoft/powershell/7/Modules
2020-06-08T12:33:20.0751693Z ##[endgroup]
2020-06-08T12:33:20.7611173Z [command]/usr/bin/az --version
2020-06-08T12:33:37.3767662Z azure-cli                          2.5.1 *
2020-06-08T12:33:37.3768195Z 
2020-06-08T12:33:37.3769862Z command-modules-nspkg              2.0.3
2020-06-08T12:33:37.3770663Z core                               2.5.1 *
2020-06-08T12:33:37.3771195Z nspkg                              3.0.4
2020-06-08T12:33:37.3771647Z telemetry                          1.0.4
2020-06-08T12:33:37.3771965Z 
2020-06-08T12:33:37.3772621Z Extensions:
2020-06-08T12:33:37.3774036Z azure-devops                      0.18.0
2020-06-08T12:33:37.3774265Z 
2020-06-08T12:33:37.3774825Z Python location '/opt/az/bin/python3'
2020-06-08T12:33:37.3775425Z Extensions directory '/opt/az/azcliextensions'
2020-06-08T12:33:37.3775874Z 
2020-06-08T12:33:37.3776276Z Python (Linux) 3.6.5 (default, Apr 30 2020, 06:21:47) 
2020-06-08T12:33:37.3776825Z [GCC 7.5.0]
2020-06-08T12:33:37.3777040Z 
2020-06-08T12:33:37.3777473Z Legal docs and information: aka.ms/AzureCliLegal
2020-06-08T12:33:37.3777717Z 
2020-06-08T12:33:37.3777925Z 
2020-06-08T12:33:37.3778363Z 
2020-06-08T12:33:37.3778917Z Please let us know how we are doing: https://aka.ms/clihats
2020-06-08T12:33:37.3779602Z and let us know if you're interested in trying out our newest features: https://aka.ms/CLIUXstudy
2020-06-08T12:33:37.3780454Z You have 2 updates available. Consider updating your CLI installation with 'sudo apt-get update && sudo apt-get install --only-upgrade -y azure-cli'. Detailed instructions can be found at https://aka.ms/doc/UpdateAzureCliApt
2020-06-08T12:33:43.0182440Z Running Azure PS Login
2020-06-08T12:33:43.0219903Z [command]/usr/bin/pwsh -Command try ***
2020-06-08T12:33:43.0220818Z             $ErrorActionPreference = "Stop"
2020-06-08T12:33:43.0221308Z             $WarningPreference = "SilentlyContinue"
2020-06-08T12:33:43.0222023Z             $output = @***
2020-06-08T12:33:43.0223016Z             $data = Get-Module -Name Az.Accounts -ListAvailable | Sort-Object Version -Descending | Select-Object -First 1
2020-06-08T12:33:43.0223849Z             $output['AzVersion'] = $data.Version.ToString()
2020-06-08T12:33:43.0224497Z             $output['Success'] = "true"
2020-06-08T12:33:43.0225061Z         ***
2020-06-08T12:33:43.0225819Z         catch ***
2020-06-08T12:33:43.0226498Z             $output['Error'] = $_.exception.Message
2020-06-08T12:33:43.0227064Z         ***
2020-06-08T12:33:43.0227702Z         return ConvertTo-Json $output
2020-06-08T12:37:14.9386562Z ***
2020-06-08T12:37:14.9410901Z   "Success": "true",
2020-06-08T12:37:14.9411268Z   "AzVersion": "1.8.1"
2020-06-08T12:37:14.9412306Z ***
2020-06-08T12:37:14.9520047Z [command]/usr/bin/pwsh -Command try ***
2020-06-08T12:37:14.9520772Z             $ErrorActionPreference = "Stop"
2020-06-08T12:37:14.9521172Z             $WarningPreference = "SilentlyContinue"
2020-06-08T12:37:14.9521803Z             $output = @***
2020-06-08T12:37:14.9522698Z             Clear-AzContext -Scope Process;
2020-06-08T12:37:14.9524621Z              Clear-AzContext -Scope CurrentUser -Force -ErrorAction SilentlyContinue;Connect-AzAccount -ServicePrincipal -Tenant *** -Credential (New-Object System.Management.Automation.PSCredential('***',(ConvertTo-SecureString *** -AsPlainText -Force))) -Environment AzureCloud | out-null;Set-AzContext -SubscriptionId *** -TenantId *** | out-null;
2020-06-08T12:37:14.9548859Z             $output['Success'] = "true"
2020-06-08T12:37:14.9549468Z         ***
2020-06-08T12:37:14.9549759Z         catch ***
2020-06-08T12:37:14.9550258Z             $output['Error'] = $_.exception.Message
2020-06-08T12:37:14.9550573Z         ***
2020-06-08T12:37:14.9551031Z         return ConvertTo-Json $output
2020-06-08T12:37:29.4206000Z ***
2020-06-08T12:37:29.4206669Z   "Success": "true"
2020-06-08T12:37:29.4207141Z ***
2020-06-08T12:37:29.4340788Z Azure PowerShell session successfully initialized
2020-06-08T12:37:29.4341672Z Login successful.
```

**Comment by asranja** [comment] 2020-06-10 04:29
@ljtill are you also facing this issue without the enable-AzPSSession: true option ?

**Comment by anwather** [comment] 2020-06-11 01:21
@asranja I have this issue as well and enable-AzPSSession is true. For me it taking over 6 minutes to log in.

**Comment by keaaa** [comment] 2020-06-18 10:53
I am also facing the same issue with login 1.1
_enable-AzPSSession=true_ it took over 7 min
_enable-AzPSSession=false_ it took 14 sec

**Comment by mattruma** [comment] 2020-09-24 01:26
It consistently takes an average of 3 minutes to complete the login.

**Comment by aksm-ms** [comment] 2020-09-24 02:59
we are looking into the issue. 
@mattruma is login taking average 3 minutues when enable-AzPSSession=true?

**Comment by mattruma** [comment] 2020-09-24 12:10
Hi @aksm-ms! Yes ... I have enable-AzPSSession=true, if you want to see how I am doing my workflow take a look at https://github.com/mattruma/MJR068/blob/master/.github/workflows/develop.yml#L17.

**Comment by harvey-k** [comment] 2020-10-02 01:08
I believe the root cause is due to the way $env:PSModulePath is configured.

The github action below is a standalone reproduction of the current issue. The second step can take several minutes to execute:

```
jobs:
  powershell-cmds:
    runs-on: ubuntu-latest
    steps: 
      - run: pwsh -Command echo \$env:PSModulePath
      # Sometimes this takes 30 seconds, but usually it takes several minutes
      - run: pwsh -Command "\$env:PSModulePath=\"/usr/share/:\$env:PSModulePath\"; echo \$env:PSModulePath;Get-Module -Name Az -ListAvailable"
```

I've opened pull request #61 to set $env:PSModulePath based on the virtual-environment filesystem layout. I'd be happy to make any changes you'd recommend.

If these changes are approved, should I put together another pull request for similar functionality within the azure/powershell repository?

**Comment by justinyoo** [comment] 2020-10-11 14:17
I've got the same issue when I use the PowerShell login. Without enabling the AzPSSession option, it took for a few secs as expected. However, if I enabled the AzPSSession option, it took more than 5-6 mins.

**Comment by justinyoo** [comment] 2020-10-11 14:41
As a workaround, I use the following combination of actions, which is much quicker (around 30-40 secs).

```yaml
    - name: Install Azure PowerShell
      shell: pwsh
      run: |
        Install-Module -Name Az -RequiredVersion ((Find-Module -Name Az)[0].Version) -AllowClobber -Scope CurrentUser -Force

    - name: Do something
      shell: pwsh
      env:
        AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      run: |
        # LOGIN TO AZURE
        $clientId = ($env:AZURE_CREDENTIALS | ConvertFrom-Json).clientId
        $clientSecret = ($env:AZURE_CREDENTIALS | ConvertFrom-Json).clientSecret | ConvertTo-SecureString -AsPlainText -Force
        $tenantId = ($env:AZURE_CREDENTIALS | ConvertFrom-Json).tenantId
        $credentials = New-Object System.Management.Automation.PSCredential($clientId, $clientSecret)
        $connected = Connect-AzAccount -ServicePrincipal -Credential $credentials -Tenant $tenantId

        # DO SOMETHING HERE
```

**Comment by harvey-k** [comment] 2020-12-03 17:42
Would it be possible to get some feedback on pull request #61 in order to address this issue?

**Comment by JAlvarezMSI** [comment] 2021-01-07 00:16
@aksm-ms Is there any update or timeline on this, having the potential of time wasted on logging in has caused us to not even want to use this action

**Comment by ljtill** [comment] 2021-02-22 10:30
Any updates on this issue, still encountering 3m 30s completion times?

**Comment by HammadKamran** [comment] 2021-03-04 16:18
Can we get an update on the performance issue? It takes up to 5-6mins on avg.

**Comment by allanmo79** [comment] 2021-03-05 12:35
update, have the same problem takes 3-4 minutes to login, with "enable-AzPSSession: true"

**Comment by maisoenaingtun** [comment] 2021-03-17 07:27
{{Login consistently takes 30s-60s to complete #20}}

**Comment by mmisztal1980** [comment] 2021-03-17 16:14
I can confirm the above 3-4min average

**Comment by jachin84** [comment] 2021-03-24 05:03
We are also experiencing this issue. It seems like there is a PR waiting that fixes this issue. What's the hold up?

**Comment by abbasalwash** [comment] 2021-04-13 13:35
We also experience the same problem. Is there a update for this issue?

**Comment by brwilkinson** [comment] 2021-04-14 16:55
Adding comment to track this issue. it might be nice if you could nominate a small list of the AZ modules to install on top of AZ.Accounts, instead of installing the whole AZ module list... Will have to do some testing.

**Comment by matsest** [comment] 2021-06-23 13:59
This is *still* an issue.

Any updates @aksm-ms @asranja?

**Comment by oallard** [comment] 2021-07-06 22:04
This is still an issue. Thank you.

**Comment by dkirrane** [comment] 2021-09-20 20:20
Still hitting this issue

**Comment by BALAGA-GAYATRI** [comment] 2021-09-24 07:35
Closing it as this seems to be a duplicate of another performance issue on the action.
Please refer the [issue](https://github.com/Azure/login/issues/119) for more updates.

**Closed by BALAGA-GAYATRI** 2021-09-24 07:35 UTC
Labels: performance-issue
