### ISSUE TITLE
Authentication timeout

### ISSUE THREAD

**Issue by fkawulok** [Azure/login#290] opened 2023-01-11 12:12 UTC
Is there a way to run a job within GitHub workflow that gets triggered after e.g. 2 hours from authentication using azure/login (PS session)? Right now, such workflow fails since the lifetime of token is ~60 minutes.

When using Connect-AzAccount with client ID and secret for the very same workflow, it runs without problems (since I believe there is a built-in refresh token mechanism).

Assuming the OIDC is based on OAUTH 2.0 and azure/login is utilizing Connect-AzAccount, I would hope there is a similar way to prevent the workflow from failing after ~1 hour?

Thank you!

**Comment by BALAGA-GAYATRI** [comment] 2023-01-13 11:02
Hi @fkawulok , Thank you for raising the issue. This is the duplicate of https://github.com/Azure/login/issues/180
As you said, currently we are supporting OIDC login session valid for 1hr which is due to no built-in refresh mechanism. Closing this issue and will be tracked in the issue that is referenced here.

**Closed by BALAGA-GAYATRI** 2023-01-13 11:02 UTC
Labels: duplicate

**Comment by BartDecker** [comment] 2023-03-15 13:26
> Hi @fkawulok , Thank you for raising the issue. This is the duplicate of #180 As you said, currently we are supporting OIDC login session valid for 1hr which is due to no built-in refresh mechanism. Closing this issue and will be tracked in the issue that is referenced here.

Is there a timeframe to get this refresh mechanism?
