### ISSUE TITLE
Upgrade to support Node.js 20

### ISSUE THREAD

**Issue by chris-witcher** [Azure/login#413] opened 2024-01-29 23:18 UTC
Currently the action only supports Node.js 16 which is now listed as deprecated.  Please update to support Node.js 20

**Comment by vytux-com** [comment] 2024-01-30 01:08
Duplicate of #357

**Comment by MoChilia** [comment] 2024-02-19 05:09
Let's track this in https://github.com/Azure/login/issues/357

**Closed by MoChilia** 2024-02-19 05:09 UTC
Labels: need-to-triage
