### ISSUE TITLE
azure/login action is not working in dependabot PRs with federated Identity

### ISSUE THREAD

**Issue by helayoty** [Azure/login#402] opened 2024-01-11 23:38 UTC
I've reported this issue before [here](https://github.com/Azure/login/issues/375) and recommendation is to use environment for the federated identity. which I did. Unfortunately, I'm still getting the same error when only with the automated `dependabot` PRs (other PRs are working fine). The login fails with the following error:

```
Error: Login failed with Error: Using auth-type: SERVICE_PRINCIPAL. Not all values are present. Ensure 'client-id' and 'tenant-id' are supplied.. Make sure 'az' is installed on the runner. If 'enable-AzPSSession' is true, make sure 'pwsh' is installed on the runner together with Azure PowerShell module. Double check if the 'auth-type' is correct. Refer to https://github.com/Azure/login#readme for more information.
```
**More info**
- Runner: GitHub-hosted runners. Linux.
- The screenshot of federated identity settings in Azure Portal: 
![Screenshot 2024-01-11 at 3 37 03 PM](https://github.com/Azure/login/assets/31887807/4ff339f6-799a-4ef6-bebf-ccf32e8b2bf7)

 - Workflow file example:
 
 ```yaml
name: test

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  workflow_dispatch: {}
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  GO_VERSION: "1.20"

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
jobs:
  e2e-tests:
  runs-on: ubuntu-latest
    environment: e2e-test
    steps:
      - name: Set up Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION  }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - uses: azure/login@v1.5.1
         with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
```

- Rerun workflow with debug mode.

```log
##[debug]Evaluating condition for step: 'Run azure/login@v1.5.1'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Run azure/login@v1.5.1
##[debug]Loading inputs
##[debug]Evaluating: secrets.AZURE_CLIENT_ID
##[debug]Evaluating Index:
##[debug]..Evaluating secrets:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'AZURE_CLIENT_ID'
##[debug]=> null
##[debug]Result: null
##[debug]Evaluating: secrets.AZURE_TENANT_ID
##[debug]Evaluating Index:
##[debug]..Evaluating secrets:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'AZURE_TENANT_ID'
##[debug]=> null
##[debug]Result: null
##[debug]Evaluating: secrets.AZURE_SUBSCRIPTION_ID
##[debug]Evaluating Index:
##[debug]..Evaluating secrets:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'AZURE_SUBSCRIPTION_ID'
##[debug]=> null
##[debug]Result: null
##[debug]Loading env
Run azure/login@v1.5.1
Error: Login failed with Error: Using auth-type: SERVICE_PRINCIPAL. Not all values are present. Ensure 'client-id' and 'tenant-id' are supplied.. Make sure 'az' is installed on the runner. If 'enable-AzPSSession' is true, make sure 'pwsh' is installed on the runner together with Azure PowerShell module. Double check if the 'auth-type' is correct. Refer to https://github.com/Azure/login#readme for more information.
##[debug]Error: Using auth-type: SERVICE_PRINCIPAL. Not all values are present. Ensure 'client-id' and 'tenant-id' are supplied.
##[debug]    at LoginConfig.validate (/home/runner/work/_actions/azure/login/v1.5.1/lib/common/LoginConfig.js:10[2](https://github.com/Azure/gpu-provisioner/actions/runs/7495749053/job/20406451727#step:6:2):2[3](https://github.com/Azure/gpu-provisioner/actions/runs/7495749053/job/20406451727#step:6:3))
##[debug]    at /home/runner/work/_actions/azure/login/v1.[5](https://github.com/Azure/gpu-provisioner/actions/runs/7495749053/job/20406451727#step:6:5).1/lib/main.js:53:31
##[debug]    at Generator.next (<anonymous>)
##[debug]    at fulfilled (/home/runner/work/_actions/azure/login/v1.5.1/lib/main.js:2[8](https://github.com/Azure/gpu-provisioner/actions/runs/7495749053/job/20406451727#step:6:8):58)
##[debug]Node Action run completed with exit code 1
##[debug]AZURE_HTTP_USER_AGENT='GITHUBACTIONS/AzureLogin@v1_Azure/gpu-provisioner'
##[debug]AZUREPS_HOST_ENVIRONMENT='GITHUBACTIONS/AzureLogin@v1_Azure/gpu-provisioner'
##[debug]AZURE_HTTP_USER_AGENT=''
##[debug]AZUREPS_HOST_ENVIRONMENT=''
##[debug]Finishing: Run azure/login@v1.5.1
```

- Does it always fail while running Dependabot PRs, or sometimes it succeeds? It only fails with Dependabot automated PRs

**Comment by YanaXu** [comment] 2024-01-12 02:54
Hi @helayoty , 
It's by design of GitHub and Dependabot. Dependabot can't read the default action secrets.
You can find the detail discussion in this [issue](https://github.com/dependabot/dependabot-core/issues/5464).
Dependabot has its own secrets settings like this [comment](https://github.com/dependabot/dependabot-core/issues/5464#issuecomment-1219132363). You can try it.

I'll close this issue. Feel free to reopen it if you have further questions.

**Closed by YanaXu** 2024-01-12 02:54 UTC
Labels: need-to-triage
