### ISSUE TITLE
Azure login with creds is no more working for certificates

### ISSUE THREAD

**Issue by Ravindra-R-reddy** [Azure/login#500] opened 2024-12-10 13:02 UTC
Hello,
name: Check Az Login
uses: azure/login@v2
with:
creds: ${{secrets.AZURE_CREDENTIALS}}
and AZURE_CREDENTIALS contains
{
"clientId": "ca",
"clientSecret": "PATH TO /spn.pem",
"subscriptionId": "a1",
"tenantId": "******************",
"resourceManagerEndpointUrl": "https://management.azure.com/"
}

*** Azure login used to work for both client secrets and certificates earlier ***
The reason why it failed to login with certificate now is because starting from Azure CLI version 2.67.0 (https://github.com/Azure/azure-cli/issues/30283), the --password parameter for az login no longer accepts service principal certificates. Instead, use the new --certificate parameter to pass a service principal certificate.

*** I believe the below code needs to be fixed to check for client secrets or certificates and set the parameters accordingly ****

async loginWithSecret(args: string[]) {
        core.info("Note: Azure/login action also supports OIDC login mechanism. Refer https://github.com/azure/login#configure-a-service-principal-with-a-federated-credential-to-use-oidc-based-authentication for more details.")
        args.push(`--password=${this.loginConfig.servicePrincipalSecret}`);
        await this.callCliLogin(args, 'service principal with secret');
    }

**Comment by MoChilia** [comment] 2024-12-10 13:09
Duplicate of https://github.com/Azure/login/issues/496. Let's track the issue there.

**Closed by MoChilia** 2024-12-10 13:09 UTC
Labels: question
