### ISSUE TITLE
Deprecation message in SP creation

### ISSUE THREAD

**Issue by SeryioGonzalez** [Azure/login#314] opened 2023-05-05 15:26 UTC
Option '--sdk-auth' has been deprecated and will be removed in a future release.

**Comment by MoChilia** [comment] 2023-05-30 03:22
Hi @SeryioGonzalez! We are actively addressing the situation you mentioned and will provide a resolution soon. Thank you for bringing it to our attention.

**Comment by jiasli** [comment] 2023-06-01 03:36
Duplicate of #223

**Closed by jiasli** 2023-06-01 03:36 UTC
Labels: need-to-triage
