### ISSUE TITLE
I am unable to login into azure using github actions.

### ISSUE THREAD

**Issue by GuptajiMLOps** [Azure/login#440] opened 2024-04-29 18:56 UTC
- name: Login via Az module
      uses: azure/login@v1.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

**using this YAML script**

**and passing this JSON file in secrets.**

{
"clientId":"xxxxxx",
"clientSecret":"xxxxxx",
"subscriptionId":"xxxxxx",
"tenantId":"xxxxxx",
"activeDirectoryEndPointUrl":"https://login.microsoftonline.com",
"resourceManagerEndpointUrl":"https://management.azure.com/",
"activeDirectoryGraphResourceId":"https://graph.windows.net/",
"sqlManagementEndPointUrl":"https://management.core.windows.net:8443/",
"galleryEndpointUrl":"https://gallery.azure.com/",
"managementEndpointUrl":"https://management.core.windows.net/"
}

Getting this error.

**Error: Az CLI Login failed. Please check the credentials. For more information refer https://aka.ms/create-secrets-for-GitHub-workflows
Error: Error: Error: The process '/usr/bin/az' failed with exit code 1**

**Comment by MoChilia** [comment] 2024-04-30 01:48
Hi @GuptajiMLOps, could you please verify the validity of your credentials? If they are confirmed valid, please update to the latest `azure/login@v2` and share the error messages here for further clarification.

:exclamation:  **Always handle your secrets with care and avoid sharing them publicly.** I have already deleted your credentials, but **please refresh your client secret** in case it was exposed to anyone else.

**Comment by JackBruceShell** [comment] 2024-05-10 13:06
I am also facing this issue with azure/login@v1 where the error is outputting the below:

Error: Login failed with Error: The process '/home/DEVUSAISUser/.local/bin/az' failed with exit code 1. Double check if the 'auth-type' is correct. Refer to https://github.com/Azure/login#readme for more information.

If i change to azure/login@v2, then i get the below error:

Run azure/login@v2
/home/DEVUSAISUser/actions-runner/externals/node20/bin/node: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /home/DEVUSAISUser/actions-runner/externals/node20/bin/node)
/home/DEVUSAISUser/actions-runner/externals/node20/bin/node: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/DEVUSAISUser/actions-runner/externals/node20/bin/node)
/home/DEVUSAISUser/actions-runner/externals/node20/bin/node: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /home/DEVUSAISUser/actions-runner/externals/node20/bin/node)
/home/DEVUSAISUser/actions-runner/externals/node[20](https://github.com/sede-x/iPaaS-Sandbox/actions/runs/9031964212/job/24819236079#step:2:21)/bin/node: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/DEVUSAISUser/actions-runner/externals/node20/bin/node)
/home/DEVUSAISUser/actions-runner/externals/node20/bin/node: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /home/DEVUSAISUser/actions-runner/externals/node20/bin/node)
/home/DEVUSAISUser/actions-runner/externals/node20/bin/node: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /home/DEVUSAISUser/actions-runner/externals/node20/bin/node)

**Comment by YanaXu** [comment] 2024-05-11 03:07
> ome/$username/actions-runner/exte

Hi @JackBruceShell ,
could you please provide your runner information and the sample workflow file?

**Comment by YanaXu** [comment] 2024-07-25 04:21
I'll close this issue since no feedback from author for a long time. Feel free to reopen it.

**Closed by YanaXu** 2024-07-25 04:21 UTC
Labels: question, needs-author-feedback
