### ISSUE TITLE
Login failed with the same credentials

### ISSUE THREAD

**Issue by csaba-kovacs** [Azure/login#295] opened 2023-01-30 12:19 UTC
I'm facing an issue where the same AZ login step fails, but I'm using the same credentials in the secret.

![Screenshot 2023-01-30 at 14 15 38](https://user-images.githubusercontent.com/88077449/215474731-0779ccf3-0bc0-4f78-a39f-e73bde597cee.png)

![Screenshot 2023-01-30 at 14 15 12](https://user-images.githubusercontent.com/88077449/215474738-fca12f0a-7d4f-4dbd-b4d2-dda595e16a29.png)

Both step contains only the creds option:
![Screenshot 2023-01-30 at 14 34 11](https://user-images.githubusercontent.com/88077449/215478494-446a9a11-cf5f-41f2-9247-371a70710394.png)

Any idea where this comes from? Why does the creds fields look different?

**Comment by csaba-kovacs** [comment] 2023-01-30 12:26
`- name: Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_DEV }}`

**Comment by csaba-kovacs** [comment] 2023-01-30 12:26
Both step has no options other then creds
![Screenshot 2023-01-30 at 14 25 46](https://user-images.githubusercontent.com/88077449/215476609-cebf478d-f7db-4f4e-a313-bb6642eb470a.png)

**Comment by BALAGA-GAYATRI** [comment] 2023-02-01 12:05
Hi, can you please share your workflow for more details?

**Comment by csaba-kovacs** [comment] 2023-02-03 11:40
Last time it worked on 13th of december 2022. This is the DEV env. workflow. Litereally looks the same for test/prod as well.
![Screenshot 2023-02-03 at 13 38 32](https://user-images.githubusercontent.com/88077449/216594275-1833cbf2-5e6d-4b31-9502-c216910fd676.png)

**Comment by rituparnop** [comment] 2023-02-11 15:22
Facing same issue. Suddenly creds stopped working last week without any changes. Similar to https://github.com/Azure/login/issues/205. Tried creating new creds but that failed too. This is second action in workflows just after checkout. Need an urgent fix for this as whole build is broken now.

**Comment by BALAGA-GAYATRI** [comment] 2023-02-15 12:15
Can you please confirm if you are generating credentials using - 
```

   az ad sp create-for-rbac --name "myApp" --role contributor \
                            --scopes /subscriptions/{subscription-id}/resourceGroups/{resource-group} \
                            --sdk-auth
```
as mentioned in the readme? Please make sure you are including `--sdk-auth` without which the action throws error.

**Comment by csaba-kovacs** [comment] 2023-02-15 14:56
> 

Can this be done from the portal? I don't have full admin privileges do recreate or add the `--sdk-auth` option. And i would still not understand how did it work before. The app was created from the portal.

**Comment by rituparnop** [comment] 2023-02-15 15:25
Working creds created using `--sdk-auth` option.
Anyway solved this by installing azure cli separately before azure/login step.
```
      - name: Install Azure cli
        run: |
          sudo apt-get install ca-certificates curl apt-transport-https lsb-release gnupg
          curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
          AZ_REPO=$(lsb_release -cs)
          echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
          sudo apt-get update
          sudo apt-get install azure-cli
```

**Comment by csaba-kovacs** [comment] 2023-02-16 13:12
> Working creds created using `--sdk-auth` option. Anyway solved this by installing azure cli separately before azure/login step.
> 
> ```
>       - name: Install Azure cli
>         run: |
>           sudo apt-get install ca-certificates curl apt-transport-https lsb-release gnupg
>           curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
>           AZ_REPO=$(lsb_release -cs)
>           echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
>           sudo apt-get update
>           sudo apt-get install azure-cli
> ```

You added the `--sdk-auth` first then installed the CLI before the login step?

**Comment by BALAGA-GAYATRI** [comment] 2023-02-17 17:03
@csaba-kovacs you might need to try OIDC login. Readme has more details on getting started with it.

**Comment by MrCliff** [comment] 2023-03-08 08:53
For us, the same error seems to occur randomly on some workflow runs but then go away after retrying the run. We use the Azure PS session.
![kuva](https://user-images.githubusercontent.com/18216650/223665973-98a4481f-8a31-4301-8820-a84586ca10af.png)

And actually it seems you have the exactly same problem in [your pipelines](https://github.com/Azure/login/actions/runs/4360749545/jobs/7623968716) which seems to go away after [another run on the same version](https://github.com/Azure/login/actions/runs/4361612356).

**Comment by BALAGA-GAYATRI** [comment] 2023-03-08 18:36
@MrCliff this could be the problem with Az ps module latest version which again seems to be intermittent. I will keep a note of it and see if something could be done here.

**Comment by kye** [comment] 2023-03-09 22:26
We experience the same intermittent errors as @MrCliff.

Is the fix to switch to CLI?

`Error: Azure PowerShell Login failed. Please check the credentials and make sure az is installed on the runner. For more information refer https://aka.ms/create-secrets-for-GitHub-workflows"  `

**Comment by MoChilia** [comment] 2023-04-28 07:30
Hi @csaba-kovacs,
It appears that the issue is due to the credential not being correctly passed to the workflow. This can occur when the workflow is triggered by a pull request from a forked repository. Please verify if this is the case for you. If it is, then you should also add the credential to the forked repo.

**Comment by MrCliff** [comment] 2023-05-01 07:04
> We experience the same intermittent errors as @MrCliff. We raised the issue with GitHub Support and they directed us here.
> 
> Is the fix to switch to CLI?
> 
> `Error: Azure PowerShell Login failed. Please check the credentials and make sure az is installed on the runner. For more information refer https://aka.ms/create-secrets-for-GitHub-workflows" `

@kye Yes, at least it worked for us. We switched to CLI and our pipelines have been working fine since.

**Comment by michaelmcneilnet** [comment] 2023-05-17 16:40
I have noticed this issue when executing a login at the same time from multiple runs.

When a branch is merged to main, I have a workflow which logs into azure with this action, then deploys the main branch.

If I merge a few dependabot PRs at the same time, only one of the logins succeeds, and all the others fail.

**Comment by YanaXu** [comment] 2023-05-31 10:58
Hi @michaelmcneilnet & @kye & @kye , 

Could you share more information with us? We're trying to reproduce this issue.

- Do you run all the jobs on a self-hosted runner to a GitHub-hosted runner? Linux or Windows?
- Do you notice that all the jobs are started at the same time or they are run one by one?
- Does the issue happen when several jobs run at the same time, or it happens when you run a single job more than one time?

**Comment by helayoty** [comment] 2023-11-21 00:42
I'm facing the same issue while running Dependabot PRs only, other PRs are working fine. The login will fail with the following error:

`
Error: Az CLI Login failed. Please check the credentials and make sure az is installed on the runner. For more information refer https://aka.ms/create-secrets-for-GitHub-workflows
`
We added federated identity to handle dependabot branches similar to `dependabot/github_actions/*` patterns but still fail.


- Running on GitHub-hosted runners. Linux.

**Comment by YanaXu** [comment] 2023-11-23 02:22
> dabot branches s

@helayoty I think you're describing a different issue. Could you open a new issue for your case and provide the following information? (please mask the confidential details)

- The screenshot of your federated identity settings in Azure Portal 
- Your workflow file example
- Run your workflow again with debug mode. Provide the debug log.
- Does it always fail while running Dependabot PRs or sometimes it succeeds?

**Comment by helayoty** [comment] 2023-11-23 04:34
> > dabot branches s
> 
> @helayoty I think you're describing a different issue. Could you open a new issue for your case and provide the following information? (please mask the confidential details)
> 
> * The screenshot of your federated identity settings in Azure Portal
> * Your workflow file example
> * Run your workflow again with debug mode. Provide the debug log.
> * Does it always fail while running Dependabot PRs or sometimes it succeeds?

Here you go https://github.com/Azure/login/issues/375

**Closed** 2024-03-01 06:29 UTC
Labels: question, needs-author-feedback
