### ISSUE TITLE
Azure cli version 2.67.0 no longer supporting --password for client certificate as secret. And azure/login@v2 is started failing.

### ISSUE THREAD

**Issue by surya2155** [Azure/login#498] opened 2024-12-03 07:34 UTC
Hello,

We work with client Certificate as Secret when AZ login with SPN. We haven't faced any issue till last week when this action was using Azcli version < 2.67.0. 
Due to the latest release of Az cli, It started failing with below error:

Attempting Azure CLI login by using service principal with secret...
Error: AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app '***'. 

Error: The error may be caused by passing a service principal certificate with --password. Please note that --password no longer accepts a service principal certificate. To pass a service principal certificate, use --certificate instead.

**Can we expect a new release from Azure/login Action to support this recent change? Or can we have an option to use a custom Azure Cli version which we can set to < 2.67.0??**

Right now, as a workaround I am downgrading the Az cli version and using the same action. I have to use this azure/login action because it's the mandatory pre-requisite step before using azure/aks-set-context@v3.

![Image](https://github.com/user-attachments/assets/1c9c9643-24f0-47f2-b2d9-72eb0319ba3e)

```
- name: Downgrade Az cli version
      shell: bash
      run: |
            AZ_DIST=$(lsb_release -cs)
            AZ_VER=2.65.0
            sudo apt-get install azure-cli=${AZ_VER}-1~${AZ_DIST} --allow-downgrades
            az version

 - uses: azure/login@v1
      with:
        creds: "{
          \"clientId\": \"${{ env.ARM_CLIENT_ID }}\",
          \"clientSecret\": \"key.pem\",
          \"subscriptionId\": \"${{ env.ARM_SUBSCRIPTION_ID }}\",
          \"tenantId\": \"${{ env.ARM_TENANT_ID }}\"
          }"
```

**Comment by MoChilia** [comment] 2024-12-03 07:37
Duplicate of https://github.com/Azure/login/issues/496. Let's track the issue there.

**Closed by MoChilia** 2024-12-03 07:37 UTC
Labels: question
